// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt0c98-ee2xeOnyBmzVdrXMF8YAasabFY',
    appId: '1:51827100876:web:1951b259159f9c35380669',
    messagingSenderId: '51827100876',
    projectId: 'instagram-clone-dacf4',
    authDomain: 'instagram-clone-dacf4.firebaseapp.com',
    storageBucket: 'instagram-clone-dacf4.appspot.com',
    measurementId: 'G-9K0JR4H2Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_7_uj9fITsza60BPHZrdmwHBn0C1sbY4',
    appId: '1:51827100876:android:2dc67ad76b23b310380669',
    messagingSenderId: '51827100876',
    projectId: 'instagram-clone-dacf4',
    storageBucket: 'instagram-clone-dacf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoEutVC_v8r6i8WAhGQq92InQw442AyLQ',
    appId: '1:51827100876:ios:13af391b864684f1380669',
    messagingSenderId: '51827100876',
    projectId: 'instagram-clone-dacf4',
    storageBucket: 'instagram-clone-dacf4.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoEutVC_v8r6i8WAhGQq92InQw442AyLQ',
    appId: '1:51827100876:ios:561fe9053a0d01c2380669',
    messagingSenderId: '51827100876',
    projectId: 'instagram-clone-dacf4',
    storageBucket: 'instagram-clone-dacf4.appspot.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
